"""empty message

Revision ID: 79700b91ffc3
Revises: 
Create Date: 2020-12-08 22:58:01.290681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79700b91ffc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
