"""empty message

Revision ID: f503b3ff01b8
Revises: 7d2f28d920f0
Create Date: 2020-12-01 18:17:53.506192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f503b3ff01b8'
down_revision = '7d2f28d920f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
